# Generated by Django 4.0.6 on 2022-08-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_posts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostUp',
        ),
    ]
