# Generated by Django 4.0.6 on 2022-08-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followercount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
            ],
        ),
    ]
